# This image is created from test/Dockerfile
image: registry.gitlab.com/sosy-lab/software/cpu-energy-meter/test:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - make clean

stages:
  - build
  - test
  - dist

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - cpu-energy-meter

test:
  stage: test
  script:
    - make test

deb:
  stage: dist
  script:
    - scripts/create_deb.sh
  artifacts:
    paths:
      - "*.deb"
