language: C
compiler: gcc

os: linux

addons:
  apt:
    packages:
      - libcap-dev

script:
  - make clean
  - make test

notifications:
  email:
    recipients:
      - TBunk1989@gmail.com
    on_success: change
    on_failure: always
