language: C
compiler: gcc

os: linux

addons:
  apt:
    packages:
      - libcap-dev

script:
  - make clean
  - make test

notifications:
  email:
    recipients:
      - benchexec-dev@googlegroups.com
    on_success: change
    on_failure: always
